package agentipc

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"
)

// Message is the unit of peer IPC (design §13 Context layer 3: IPC Messages).
// It carries a topic/payload plus a correlation id for request/reply pairing.
type Message struct {
	// ID is the unique message id (generated by the bus).
	ID string
	// From is the sender agent id.
	From string
	// To is the target agent id ("" = broadcast to subscribers).
	To string
	// Topic is the message subject (e.g. "verify-conclusion", "handoff-task").
	Topic string
	// CorrelationID pairs a reply with its request (empty for fire-and-forget).
	CorrelationID string
	// Payload is the message body.
	Payload any
	// At is the send timestamp.
	At time.Time
}

// Handler delivers a message to an agent. The handler receives the message
// and may return a reply (for Request/Reply) or an error.
type Handler func(ctx context.Context, msg *Message) (*Message, error)

// ErrAgentNotRegistered is returned when a target agent is not on the bus.
var ErrAgentNotRegistered = errors.New("agentipc: agent not registered")

// ErrNoHandler is returned when an agent has no registered handler.
var ErrNoHandler = errors.New("agentipc: no handler")

// ErrTimeout is returned when a request does not get a reply in time.
var ErrTimeout = errors.New("agentipc: request timed out")

// ErrInvalidMessage is returned for a malformed message.
var ErrInvalidMessage = errors.New("agentipc: invalid message")

// Bus is the peer-to-peer IPC message bus (Kernel IPC pillar). It maps agent
// IDs to handlers and provides the full primitive set: Send / Request / Reply
// / Delegate / Handoff / Subscribe. All state is serialized under mu; the
// pending-request table uses per-request channels for reply correlation.
type Bus struct {
	mu       sync.RWMutex // guards handlers, subscribers, pending
	handlers map[string]Handler
	// subscribers[topic] = list of subscriber agent ids
	subscribers map[string][]string
	// pending[correlationID] = reply channel (buffered 1)
	pending map[string]chan *Message
	// pendingErr[correlationID] = stashed handler error (surfaces when a
	// nil reply is delivered to signal an error)
	pendingErr map[string]error
	idSeq      uint64
	now        func() time.Time
}

// NewBus creates an empty IPC bus.
func NewBus() *Bus {
	return &Bus{
		handlers:    make(map[string]Handler),
		subscribers: make(map[string][]string),
		pending:     make(map[string]chan *Message),
		pendingErr:  make(map[string]error),
		now:         time.Now,
	}
}

// WithClock injects a controllable clock for deterministic tests.
func (b *Bus) WithClock(now func() time.Time) *Bus {
	b.mu.Lock()
	defer b.mu.Unlock()
	if now != nil {
		b.now = now
	}
	return b
}

// Register associates a handler with an agent id. Re-registering replaces the
// previous handler (idempotent for restart/resurrection).
func (b *Bus) Register(agentID string, h Handler) error {
	if agentID == "" {
		return fmt.Errorf("agentipc: agent id required")
	}
	if h == nil {
		return fmt.Errorf("agentipc: handler must not be nil")
	}
	b.mu.Lock()
	defer b.mu.Unlock()
	b.handlers[agentID] = h
	return nil
}

// Unregister removes an agent from the bus. Pending requests to this agent
// will fail with ErrAgentNotRegistered.
func (b *Bus) Unregister(agentID string) {
	b.mu.Lock()
	defer b.mu.Unlock()
	delete(b.handlers, agentID)
	// Remove from subscriber lists.
	for topic, subs := range b.subscribers {
		out := subs[:0]
		for _, s := range subs {
			if s != agentID {
				out = append(out, s)
			}
		}
		b.subscribers[topic] = out
	}
}

// nextIDLocked generates a unique message id. Caller must hold b.mu.
func (b *Bus) nextIDLocked() string {
	b.idSeq++
	return fmt.Sprintf("msg-%d", b.idSeq)
}
